version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
<<<<<<< HEAD
      day: "tuesday"
=======
      day: "tuesday"
>>>>>>> 681dba2 (Adding dependabot, PR template and setting up gh actions)
